### ISSUE TITLE
File that is mentioned in 'ignored_key_prefixes' is removed after sync

### ISSUE THREAD

**Issue by stefanschindler** [translation/laravel#18]
Hi!
I am using the v1.12 of your package, and PHP 7.3.23.

I have a translation.php file as follows:

```
	...

	'source_locale' => 'de',

    'target_locales'       => ['en'],

    /*
    |--------------------------------------------------------------------------
    | # Ignored PHP key prefixes.
    |--------------------------------------------------------------------------
    |
    | Ex: * 'validation':        ignore the whole validation.php file.
    |     * 'validation.custom': ignore the "custom" subtree in validation.php file.
    |     * 'subfolder/more':    ignore the whole subfolder/more.php file.
    |
    */
    'ignored_key_prefixes' => ['legacy', 'validation'],

	...
```

So, I want to translate from german to english.
The `validation.php` file is only available in the `en`, but not in the `de` folder (as I just need this file for internalt tests). So I have some structure like this:

```
de/
	file1.php
	file2.php
en/
	file1.php
	validation.php
```

But although `validation` is mentioned in the `ignored_key_prefixes`, the `en/validation.php` file is removed after I call `php artisan translation:sync`. My structure after syncing is:

```
de/
	file1.php
	file2.php
en/
	file1.php
	file2.php
```

If I understand correctly, the file `en/validation.php` should not be touched, because it is ignored, so I think I found a bug here?

**Comment by MichaelHoste** [comment]
Hi @stefanschindler,

The main purpose of `ignored_key_prefixes` is to ignore some keys or files from the source locale, not from the target locales. It's convenient when you don't want to translate some files.

Target locale files are always recreated from scratch using the existing source keys and the translations from Translation.io.

The code is here: https://github.com/translation/laravel/blob/master/src/TranslationSaver.php#L41-L42

The reason is that we don't want a target PHP file to stay in your codebase when it's removed from the source (it was actually a bug at some point).

Maybe we could add an option to ignore the deletion of some files from the target directory. But we won't be able to use the `ignored_key_prefixes` for that situation because it could also be a prefix for a specific sub-key, and not a complete file. And that would make things too complex to manage.

Can I ask why you need a `validation.php` file in the target and not in the source? What is your use case here?

**Comment by stefanschindler** [comment]
Hi @MichaelHoste ,

thanks for your response. It's not a big issue for me. It seems I just misunderstood the usage of the `ignored_key_prefixes`.

I don't need the `validation.php` file in the source, it is only required for running my unit tests, so I thought, before using a german translation, I just exclude it from the translation library.

But it's no problem to include a german validation file, I just thought I found some kind of bug.

Thanks for the cool package! It really speeds up our translation process.

**Comment by MichaelHoste** [comment]
> thanks for your response. It's not a big issue for me. It seems I just misunderstood the usage of the ignored_key_prefixes.

It was not clear enough :/
Thanks to your feedback, we slightly improved the documentation to avoid this confusion in the future.

> But it's no problem to include a german validation file, I just thought I found some kind of bug.

I'm glad you could make it work without any change in the package. We could add a new option to exclude some target files, but I'm not sure it would be used a a lot. We'll wait to see if this issue happens again in the future.

> Thanks for the cool package! It really speeds up our translation process.

That's really great! We're glad to hear it :-)
Have a great day!
