### ISSUE TITLE
php8 issue

### ISSUE THREAD

**Issue by jouniikaheimo** [translation/laravel#22]
i got error php 8

  Gettext\Utils\FunctionsScanner::Gettext\Utils\{closure}(): Argument #1 ($carry) must be passed by reference, value given

**Comment by MichaelHoste** [comment]
Hi @jouniikaheimo 

Thanks for this issue, we'll look at this.

I noticed that you managed to fix the issue and initialize your project.

It would help to know how you did it (go back to PHP 7?)

**Comment by jouniikaheimo** [comment]
yes i go to back php 7.. but i think lasted gettext/gettext fix issue that now support php8

**Comment by MichaelHoste** [comment]
Unfortunately for the moment we need to stick the the [4.x](https://github.com/php-gettext/Gettext/tree/4.x) branch of [php-gettext/Gettext](https://github.com/php-gettext/Gettext) because of big internal changes and the missing Blade scanner in 5.x.

We'll investigate what went wrong with PHP 8 and try to create a pull request to fix it on the 4.x branch.

**Comment by MichaelHoste** [comment]
The pull request is created. It was something quite easy to fix: https://github.com/php-gettext/Gettext/pull/266

I'll bump this package as soon as they create a new release. Thank you for the feedback!

**Comment by MichaelHoste** [comment]
The [pull request](https://github.com/php-gettext/Gettext/pull/266) was already merged, kudos to @oscarotero reactivity!

The dependencies are updated and [https://github.com/translation/laravel/releases/tag/v1.14](v.1.14) is now compatible with PHP 8
