### ISSUE TITLE
How do I add new segments to a pre-existing project?

### ISSUE THREAD

**Issue by antonhedling** [translation/laravel#29]
Hello,

This isn't a bug report but simply a question. We've been using this package for a while now and everything works well. However I need to add a couple of hundred new translations (that I already have as .php files). However, when I run the sync command, I only get the source texts imported. All my translation files are overwritten with empty data from translation.io.
  I guess this is the way it's intended since it seems to use translation.io as a "source of truth". 
  
But still, I don't really have the time to add all these manually. Is there a way to sort of "re-init" or sync with the codebase as the source? Or is the only solution to create a new project from scratch?

**Comment by MichaelHoste** [comment]
Hi @antonhedling,

You're right, the synchronization only push the source and receive the corresponding translations (the existing ones will be overwritten).

You have several ways to do what you want:

**1. Create and `init` a new project**

Since your entire updated project is on your code, you can just create and initialize a new project on Translation.io. You will just need to invite your collaborators again (just a few clicks).

However, your changes history will be lost.

The process is similar as this one: https://github.com/translation/laravel#edit-language

**2. Use our API**

You can create a small script to go through your manually updated PHP files, and use our API to update them on Translation.io

The useful endpoints will be: 

 * https://translation.io/docs/api#segments-index
 * https://translation.io/docs/api#segments-update

It's quite easy but if you don't mind to lose your history,  the first option is faster.

I hope it helps!
