### ISSUE TITLE
Laravel 9 upgrade

### ISSUE THREAD

**Issue by rbruhn** [translation/laravel#30]
In reading the Laravel 9 upgrade, they are moving the lang directory from resources/lang to the project directory.
Are you going to implement this change?

**Comment by MichaelHoste** [comment]
Hi @rbruhn,

To be honest, we didn't notice this directory change in Laravel 9.

But since we use `$this->application['path.lang'];` and not the hard-coded directory name, it should works. Did you have any issue with this?

If you use GetText, you may also need to update your config file accordingly here: https://github.com/translation/laravel/blob/df2595eb65e33b1a2f0bdfa07bdb1365b6453a60/config/translation.php#L39

Feel free to tell us if you noticed any issue with this, we may have forgotten something.

**Comment by rbruhn** [comment]
Thanks, didn't see that. Not having any issues.

**Comment by MichaelHoste** [comment]
We updated the README and some parts of the code to better reflect the new default `lang` directory in Laravel 9:

 * https://github.com/translation/laravel/commit/75dfa2c2fba8e8f7cf33431a8f69bca0d50eaf36
 * [v1.18](https://github.com/translation/laravel/releases/tag/v1.18)

Thank you for pointing this out 🙂
